@startuml
title Пошаговое взаимодействие в системе "Золотой ключик"

actor "Буратино" as B
actor "Карабас-Барабас" as KB
participant Key as K
participant Door as D

' 1. Нахождение ключа
B -> B : найтиОбъект("Key")
B --> B : Key

' 2. После того как Буратино нашёл ключ
alt Карабас догоняет, Буратино убегает
    KB -> KB : догнать(Буратино)
      KB -> KB : перехватитьКлюч(Буратино)
    B -> B : убежать()
    B -> B : скрытьКлюч()
    B --> KB : ключ не отдан
else Карабас догоняет, Буратино не убегает
    KB -> B : догнать(Буратино)
    KB -> B : перехватитьКлюч(Буратино)
    B --> KB : ключ отдан
end

' 3. Нахождение двери
B -> B : найтиОбъект("Door")
B --> B : Door
B -> D : обнаружить()

' 4. Открытие двери
B -> B : открытьДверь(Door)
  B -> D : открыть(Key)
    D -> K : compare(замок) : bool
    K --> D : true
  D --> B : true
@enduml
