@startuml
title Диаграмма состояний: Дверь

state "скрыта" as Hidden
state "найдена" as Discovered
state "открыта" as Opened


[*] --> Hidden

' Все воздействия идут в точку принятия решения
Hidden --> Discovered : обнаружить()
Discovered --> Opened : открыть(Key) [key valid]

Opened --> [*]
@enduml
