@startuml
left to right direction

actor "Буратино" as Puppet
actor "Карабас-Барабас" as Karabas

package "Система аутентификации" {
  usecase "Убежать от погони" as RunAway
  usecase "Найти ключ" as FindKey
  usecase "Найти дверь" as FindDoor
  usecase "Открыть дверь" as OpenDoor
  usecase "Скрыть ключ от Карабаса" as HideKey
  usecase "Перехватить ключ" as InterceptKey
  usecase "Догнать Буротино" as CatchUp
}

' Основные независимые действия Буротино
Puppet --> OpenDoor

' Основные независимые действия Карабаса-Барабаса
Karabas --> InterceptKey

' Зависимости внутри системы
OpenDoor <.. FindDoor : <<include>>
OpenDoor <.. FindKey : <<include>>
FindKey <.. RunAway : <<extend>> : если Карабас-Барабас погонится
FindKey <.. HideKey : <<extend>> : чтобы Карабас-Барабас не забрал ключ

InterceptKey <.. FindKey : <<include>>
CatchUp <.. InterceptKey : <<include>>
@enduml
